version: '3'

services:
  classeviva2caldav:
    build:
      context: ./
      #dockerfile: ./Dockerfile
    env_file:
      - .env
    container_name: classeviva2caldav
    volumes:
      - ./db:/usr/src/app/src/db/vol
    environment:
      - TZ=Europe/Rome
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "false"
